version: "2"

services:
  async:
    image: destructhub/project_euler
    entrypoint: elixir --no-halt stats.exs -s python
                                           -s commonlisp
                                           -s ruby
                                           -s haskell
                                           -s go
                                           -s php
                                           -s elixir
                                           -s lua
                                           -s c++
                                           -s bash
                                           -s clojure
                                           -s c
    environment:
      STATS_POOL_SIZE: #{STATS_POOL_SIZE}
    volumes:
      - .:/code

  sync:
    image: destructhub/project_euler
    command: python3 stats.py --build -s python
                                      -s commonlisp
                                      -s ruby
                                      -s haskell
                                      -s go
                                      -s php
                                      -s elixir
                                      -s lua
                                      -s c++
                                      -s bash
                                      -s clojure
                                      -s c
    volumes:
      - .:/code
  diff-sync:
    image: destructhub/project_euler
    command: ./test
    volumes:
      - .:/code
